-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 19:37:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `ativo` TINYINT NULL,
  `Professor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Professor_idx` (`Professor_id` ASC),
  CONSTRAINT `fk_Usuario_Professor`
    FOREIGN KEY (`Professor_id`)
    REFERENCES `mydb`.`Professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `id` INT NOT NULL,
  `numero` INT NULL,
  `ativo` TINYINT NULL,
  `Tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sala_Tipo1_idx` (`Tipo_id` ASC),
  CONSTRAINT `fk_Sala_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `mydb`.`Tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor_Materia` (
  `Professor_id` INT NOT NULL,
  `Materia_id` INT NOT NULL,
  `id` INT NULL,
  PRIMARY KEY (`Professor_id`, `Materia_id`),
  INDEX `fk_Professor_has_Materia_Materia1_idx` (`Materia_id` ASC),
  INDEX `fk_Professor_has_Materia_Professor1_idx` (`Professor_id` ASC),
  CONSTRAINT `fk_Professor_has_Materia_Professor1`
    FOREIGN KEY (`Professor_id`)
    REFERENCES `mydb`.`Professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Materia_Materia1`
    FOREIGN KEY (`Materia_id`)
    REFERENCES `mydb`.`Materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `Professor_Materia_Professor_id` INT NOT NULL,
  `Professor_Materia_Materia_id` INT NOT NULL,
  `Sala_id` INT NOT NULL,
  `id` INT NULL,
  `data` DATE NULL,
  `dataLimite` DATE NULL,
  PRIMARY KEY (`Professor_Materia_Professor_id`, `Professor_Materia_Materia_id`, `Sala_id`),
  INDEX `fk_Professor_Materia_has_Sala_Sala1_idx` (`Sala_id` ASC),
  INDEX `fk_Professor_Materia_has_Sala_Professor_Materia1_idx` (`Professor_Materia_Professor_id` ASC, `Professor_Materia_Materia_id` ASC),
  CONSTRAINT `fk_Professor_Materia_has_Sala_Professor_Materia1`
    FOREIGN KEY (`Professor_Materia_Professor_id` , `Professor_Materia_Materia_id`)
    REFERENCES `mydb`.`Professor_Materia` (`Professor_id` , `Materia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Materia_has_Sala_Sala1`
    FOREIGN KEY (`Sala_id`)
    REFERENCES `mydb`.`Sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
